AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - '**/Gemfile'
    - 'vendor/**/*'

Layout/EmptyLinesAroundArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/concerns/*'
    - 'app/controllers/concerns/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/StringMethods:
  Enabled: true
