language: ruby
cache: bundler
rvm: 2.5.0
bundler_args: "--without production development"
services: postgresql

env:
  - COMMAND="rspec"
  - COMMAND="rubocop -D -f simple"

matrix:
  fast_finish: true
  allow_failures:
    - env: COMMAND="brakeman"
    - env: COMMAND="rake traceroute FAIL_ON_ERROR=1"

before_script:
  - psql -c 'create database pypagao_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - "bundle exec $COMMAND"
